### ISSUE TITLE
[Compatibility] Modded light source not destroyed.

### ISSUE THREAD

**Issue by Fokke456** [mactso/SpawnerInLight#17]
Hello! The Rose Quartz Lamp from Create (similar to a redstone lamp in function) is not destroyed by the spawner, allowing players to bypass the light source destruction system. While you can add compat for this specific case, it'd in my eyes probably better to add a whitelist for lightsources to the config so that if something like this occurs, it can be fixed in the config by the user (since it's not possible to consider all mods ever for compatibility). Cheers!

**Comment by mactso** [comment]
Funny thing is I look for *any* block registered as a light emitting block.  I'll give this a look.

Which version of minecraft are you in?

**Comment by mactso** [comment]
Okay, this is fixed for Minecraft Forge 1.20.2 thru 1.20.5.

"harderspawners-1.20.2-48.25.3.jar"

It has a list of lamp blocks in the config file now.   But you could also add non-lamp blocks.  Like dirt or stone.
It also checks for blocks that end with "_lamp" .

I appreciate that you called this to my attention!.

Please let me know if it doesn't work or has problems!.
