### ISSUE TITLE
[1.18.1] server crash due to Harder Spawner (apparently)

### ISSUE THREAD

**Issue by Wedge1453** [mactso/SpawnerInLight#4]
[crash report.txt](https://github.com/mactso/SpawnerInLight/files/7985462/crash.report.txt)

**Comment by mactso** [comment]
Thanks, I'll look into this.

**Comment by mactso** [comment]
Hi!

Something called ChunkLithium may be blocking a call to get a blockstate from a block between 4 and16 blocks from the player.   Those blocks should always normally be loaded in memory.  I looked into a little further and "Lithium (Fabric)" is a fabric mod.   Did you make a forge version of it?

Here's the line it fails on:
 BlockState blockstate = sp.level.getBlockState(blockpos);


Hope this helps!
Two Guys,
Mactso

**Comment by mactso** [comment]
Okay, I added some code to verify that the area is loaded.  It *should* be cause it's only 16 blocks or less from the player and I couldn't duplicate the issue but if the area is not loaded, then I do not check for spawners now.

Also, be aware there is a similar bug in vanilla right now
https://bugs.mojang.com/browse/MC-248480

What is happening is, I'm asking minecraft for the blockstate of a block that is near the player.  And then it's sitting there for 60 seconds without returning the blockstate.  It's very generic code.  But the new version will do it's best to confirm the area is loaded before asking for the  blockstate of blocks in that area.

**Comment by Wedge1453** [comment]
yes there's a Lithium forge port, called Radium Reforged.
thanks for the fix, everything works fine now!
