### ISSUE TITLE
Server Crash 1.18

### ISSUE THREAD

**Issue by Tyrius1** [mactso/SpawnerInLight#5]
https://pastebin.com/VHjZtDhx
Server crash while flying around in creative exploring the world.
MC 1.18.1
Forge 39.0.59
Harder Spawners 1.39.0.19

**Comment by mactso** [comment]
I'm looking at the code and the only way it could fail is if the chunk next to the player wasn't loaded.  Did you see unloaded chunks near you?
I'll see about adding something to check if the chunk is loaded before asking.  But it does a "getchunk" in the routine that returns the blockstate.

**Comment by mactso** [comment]
I'm adding some code to check that the chunk is loaded before asking for blockstate.

I've submitted the new version (20) for approval.

Please let me know if it doesn't fix the issue.

**Comment by mactso** [comment]
Also be aware there is a similar crash bug in vanilla now:

https://bugs.mojang.com/browse/MC-248480

**Comment by mactso** [comment]
The other user reported this change eliminated the server crash so I'm going to close the ticket.  Please reopen it if you see the problem again.
