### ISSUE TITLE
Crash with bumblezone mod

### ISSUE THREAD

**Issue by Deathawaits4** [mactso/SpawnerInLight#8]
Hei i am getting a crash when using this mod with bumblezone. This happen regulary and removing this mod fixes the issue. Could you check the error log?
[crash-2022-08-20_23.46.46-server.txt](https://github.com/mactso/SpawnerInLight/files/9388058/crash-2022-08-20_23.46.46-server.txt)

**Comment by mactso** [comment]
I'll give this a look!

Okay-- it looks like they have a spawner block with no spawnerblockentity.   That's supposed to be "impossible"  But these things happen.   If you teleport to that location (/tp -2865 87 5010) in creative or spectator, what do you see?  Is the spawner there empty?

I'll try to get a fix out today.  If the spawnerBlock has no entity, I'll just return without trying to use it.

**Comment by mactso** [comment]
Okay, submitting version 22.1 (40.2.22.1) for approval to Curseforge.

**Comment by mactso** [comment]
Going to close this out.  Reopen if version 22.1 didn't fix the issue.
Cheers!
MacTso
